spring.application.name=SBPEmailSenderProject

server.port= 9099

spring.datasource.url=jdbc:mysql://localhost:3306/Creata DataBase 
spring.datasource.username=DataBase UserName
spring.datasource.password=Database Password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


#Email Configuration Setup
#SMPT host for sending emails via Gmail
spring.mail.host=smtp.gmail.com
#SMTP port (587 for TLS, 465 for SSL)
spring.mail.port=587

spring.mail.username=Enter Your Gmail@gmail.com
spring.mail.password=qwer uiop vbnm alfj   Take the email code forn the Google


#enabling authentication for outgoing emails
spring.mail.properties.mail.smtp.auth=true

#Enables STARTTLS for secure email sending
spring.mail.properties.mail.smtp.starttls.enable=true
